name: Make DEB
on: push

jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "./make.sh"
      - uses: actions/upload-artifact@v2
        with:
          name: "packages"
          path: "**.deb" 
